export const quotes= {
    "quotes": [
        {
            "id": 1,
            "quote": "Life isn’t about getting and having, it’s about giving and being.",
            "author": "Kevin Kruse",
            "img":"https://www.gumi-kacsa.hu/527-home_default/al-capo-kacsa.jpg",
        },
        {
            "id": 2,
            "quote": "Whatever the mind of man can conceive and believe, it can achieve.",
            "author": "Napoleon Hill",
            "img":"https://www.gumi-kacsa.hu/412-home_default/sofor-holgy-kacsa.jpg",
        },
        {
            "id": 3,
            "quote": "Strive not to be a success, but rather to be of value.",
            "author": "Albert Einstein",
            "img":"https://www.gumi-kacsa.hu/410-home_default/biciklis-kacsa.jpg",
        },
        {
            "id": 4,
            "quote": "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.",
            "author": "Robert Frost",
            "img":"https://www.gumi-kacsa.hu/527-home_default/al-capo-kacsa.jpg",
        },
        {
            "id": 5,
            "quote": "I attribute my success to this: I never gave or took any excuse.",
            "author": "Florence Nightingale",
            "img":"https://www.gumi-kacsa.hu/530-home_default/anyakacsa.jpg",
        },
        {
            "id": 6,
            "quote": "You miss 100% of the shots you don’t take.",
            "author": "Wayne Gretzky",
            "img":"https://www.gumi-kacsa.hu/533-home_default/bekakiraly-kopennyel-kacsa.jpg",
        },
        {
            "id": 7,
            "quote": "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.",
            "author": "Michael Jordan",
            "img":"https://www.gumi-kacsa.hu/88259-home_default/ali-baba-kacsa.jpg",
        },
        {
            "id": 8,
            "quote": "The most difficult thing is the decision to act, the rest is merely tenacity.",
            "author": "Amelia Earhart",
            "img":"https://www.gumi-kacsa.hu/100950-home_default/amerikai-focista-kacsa.jpg",
        },
        {
            "id": 9,
            "quote": "Every strike brings me closer to the next home run.",
            "author": "Babe Ruth",
            "img":"https://www.gumi-kacsa.hu/100884-home_default/amerikai-kacsa.jpg",
        },
        {
            "id": 10,
            "quote": "Definiteness of purpose is the starting point of all achievement.",
            "author": "W. Clement Stone",
            "img":"https://www.gumi-kacsa.hu/2835-home_default/angyal-kacsa.jpg",
        },
        {
            "id": 11,
            "quote": "We must balance conspicuous consumption with conscious capitalism.",
            "author": "Kevin Kruse",
            "img":"https://www.gumi-kacsa.hu/9398-home_default/lilalu.jpg",
        },
        {
            "id": 12,
            "quote": "Life is what happens to you while you’re busy making other plans.",
            "author": "John Lennon",
            "img":"https://www.gumi-kacsa.hu/49892-home_default/apostol-kacsa.jpg",
        },
        {
            "id": 13,
            "quote": "We become what we think about.",
            "author": "Earl Nightingale",
            "img":"https://www.gumi-kacsa.hu/179526-home_default/arnyekember-kacsa.jpg",
        },
        {
            "id": 14,
            "quote": "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover.",
            "author": "Mark Twain",
            "img":"https://www.gumi-kacsa.hu/50691-home_default/avatar-kacsa.jpg",
        },
        {
            "id": 15,
            "quote": "Life is 10% what happens to me and 90% of how I react to it.",
            "author": "Charles Swindoll",
            "img":"https://www.gumi-kacsa.hu/138885-home_default/bajor-holgy-kacsa.jpg",
        },
        {
            "id": 16,
            "quote": "The most common way people give up their power is by thinking they don’t have any.",
            "author": "Alice Walker",
            "img":"https://www.gumi-kacsa.hu/100879-home_default/bajor-kacsa.jpg",
        },
        {
            "id": 17,
            "quote": "The mind is everything. What you think you become.",
            "author": "Buddha",
            "img":"https://www.gumi-kacsa.hu/60593-home_default/balerina-kacsa.jpg",
        },
        {
            "id": 18,
            "quote": "The best time to plant a tree was 20 years ago. The second best time is now.",
            "author": "Chinese Proverb",
            "img":"https://www.gumi-kacsa.hu/138893-home_default/barista-kacsa.jpg",
        },
        {
            "id": 19,
            "quote": "An unexamined life is not worth living.",
            "author": "Socrates",
            "img":"https://www.gumi-kacsa.hu/179507-home_default/bbq-kacsa.jpg",
        },
        {
            "id": 20,
            "quote": "Eighty percent of success is showing up.",
            "author": "Woody Allen",
            "img":"https://www.gumi-kacsa.hu/179536-home_default/be-loved-kacsa-turkiz.jpg",
        },
        {
            "id": 21,
            "quote": "Your time is limited, so don’t waste it living someone else’s life.",
            "author": "Steve Jobs",
            "img":"https://www.gumi-kacsa.hu/179512-home_default/beteg-kacsa.jpg",
        },
        {
            "id": 22,
            "quote": "Winning isn’t everything, but wanting to win is.",
            "author": "Vince Lombardi",
            "img":"https://www.gumi-kacsa.hu/410-home_default/biciklis-kacsa.jpg",
        },
        {
            "id": 23,
            "quote": "I am not a product of my circumstances. I am a product of my decisions.",
            "author": "Stephen Covey",
            "img":"https://www.gumi-kacsa.hu/536-home_default/bika-kacsa.jpg",
        },
        {
            "id": 24,
            "quote": "Every child is an artist.  The problem is how to remain an artist once he grows up.",
            "author": "Pablo Picasso",
            "img":"https://www.gumi-kacsa.hu/539-home_default/birka-kacsa.jpg",
        },
        {
            "id": 25,
            "quote": "You can never cross the ocean until you have the courage to lose sight of the shore.",
            "author": "Christopher Columbus",
            "img":"https://www.gumi-kacsa.hu/545-home_default/boci-kacsa-fekete.jpg",
        },
        {
            "id": 26,
            "quote": "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
            "author": "Maya Angelou",
            "img":"https://www.gumi-kacsa.hu/60432-home_default/bokszolo-kacsa.jpg",
        },
        {
            "id": 27,
            "quote": "Either you run the day, or the day runs you.",
            "author": "Jim Rohn",
            "img":"https://www.gumi-kacsa.hu/85736-home_default/boldog-szulinapot-kacsa-lany.jpg",
        },
        {
            "id": 28,
            "quote": "Whether you think you can or you think you can’t, you’re right.",
            "author": "Henry Ford",
            "img":"https://www.gumi-kacsa.hu/50281-home_default/boszorkanymester-kacsa.jpg",
        },
        {
            "id": 29,
            "quote": "The two most important days in your life are the day you are born and the day you find out why.",
            "author": "Mark Twain",
            "img":"https://www.gumi-kacsa.hu/100931-home_default/bowling-kacsa.jpg",
        },
        {
            "id": 30,
            "quote": "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.",
            "author": "Johann Wolfgang von Goethe",
            "img":"https://www.gumi-kacsa.hu/551-home_default/buvar-kacsa.jpg",
        }
    ],
    "total": 100,
    "skip": 0,
    "limit": 30
}